import type { Metadata } from "next";
import { Maven_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "./components/view/Navbar";
import Wrapper from "./components/shared/wraper/Wrapper";
import Carousel from "./components/view/Carousel"
const inter = Maven_Pro({ subsets: ["latin"],
weight:["400","500","600","700","800","900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
        
        <Navbar/>
        <Carousel /> 
       {/* Place Carousel here */}
        {children}
        </Wrapper>
      
      </body>
    </html>
  );
}
